version: "3.8"

services:
  assets:
    image: nginx:stable-alpine
    container_name: announcement-asset
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html/assets:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - digital_net

networks:
  digital_net:
    external: true
    name: digital_net
