version: "3.8"

services:
  app:
    build: .
    container_name: announcement-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: announcement_db
      DB_USERNAME: announcement_user
      DB_PASSWORD: user123
    volumes:
      - ./:/var/www/html
      - ../announcement-asset:/var/www/html/public/assets
    command: php-fpm
    networks:
      - digital_net

  nginx:
    image: nginx:stable-alpine
    container_name: announcement-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../announcement-asset:/var/www/html/public/assets:ro
    depends_on:
      - app
    networks:
      - digital_net

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: announcement-api-swagger
    restart: unless-stopped
    environment:
      - SWAGGER_JSON=/openapi.yaml
    volumes:
      - ./public/docs/openapi.yaml:/openapi.yaml:ro
    ports:
      - "8002:8080"
    networks:
      - digital_net

networks:
  digital_net:
    external: true
    name: digital_net
