version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: announcement-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: announcement_db
      MYSQL_USER: announcement_user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - digital_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: announcement-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - digital_net

volumes:
  mysql_data:

networks:
  digital_net:
    external: true
    name: digital_net
